# NOTE: This file is generated by cuke-scale

ENV["RAILS_ENV"] ||= "test"
require File.expand_path(File.dirname(__FILE__) + '/../../../config/environment')

require 'capybara/session'

# Custom host target other than localhost:3000
# CukeScale.host = example.com

CukeScale.num_users = 1
CukeScale.offset = 0
