# NOTE: This file is generated by cuke-scale

ENV["RAILS_ENV"] ||= "test"
require File.expand_path(File.dirname(__FILE__) + '/../../../config/environment')

require 'capybara/session'

#required. TODO: this is hacky
CukeScale.rails_root = Rails.root.to_s

# Custom host target other than http://localhost:3000
# CukeScale.host = example.com

# Set number of concurrent users (default 1)
# CukeScale.num_users = 1

# Set user id offset (default 0)
# CukeScale.offset = 0
