# NOTE: This file is generated by pummel

ENV["RAILS_ENV"] ||= "test"
require File.expand_path(File.dirname(__FILE__) + '/../../../config/environment')

require 'capybara/session'

#required. TODO: this is hacky
Pummel.rails_root = Rails.root.to_s

# Custom host target other than http://localhost:3000
# Pummel.host = example.com

# Set number of concurrent users (default 1)
# Pummel.num_test_iterations = 1

# Set test_num offset (default 0)
# Pummel.offset = 0
